# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: František Kysela
title: Self-taught software developer, started as freshman in high school
email: bythedroid@gmail.com
website: Kysela.github.io

# Social links
twitter_username: ATGDroid
github_username: Kysela
# dribbble_username: jekyll
facebook_username: frantakysela
# flickr_username: jekyll
instagram_username: frantakysela
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Frank, i started to be interested in software development already in elementary school when i was deeply interested in mobile phones, especially Android based devices. I was all day long studying how Android works, how boot animation is loaded, or how user can gain root access. When i got in to high school i extended my interest by getting in to the Android community based development scene, there i launched on my own two big personal projects, got incredible amount of experience and met a lot of new people. 



  I am most skilled in: <mark>turning caffeine in to code</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
