# Site
repository: Kysela/Kysela.github.io
favicon: images/favicon.ico

# Personal info
name: František Kysela
title: Self-taught software developer, started as freshman in high school
email: bythedroid@gmail.com
website: t.me/ATGDroid
darkmode: true

# Social links
twitter_username: frantakysela
github_username: Kysela
# dribbble_username: jekyll
facebook_username: frantakysela
# flickr_username: jekyll
instagram_username: frantakysela
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Frank, or also František in czech, i started to be interested in software development already in elementary school when i had a huge passion for mobile phones, especially Android based devices. I was all day long studying how Android works, how boot animation is loaded, how you can change boot logo, or how user can gain root access. When i got in to high school i extended my interest by getting in to the Android community based development scene, there i launched on my own two big personal projects, got incredible amount of experience and met a lot of new people, since then i'm focusing mostly on my personal projects.



  I am most skilled in: <mark>c/c++</mark> and <mark>bash</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in embedded Android development and software engineering some of my other interests and hobbies are:
   - Entrepreneurship
   - Running
   - Calisthenics

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
